version: 1
build:
  main: cmd/sequencerd
accounts:
- name: alice
  coins:
  - 200000000warp
- name: bob
  coins:
  - 100000000warp
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000warp
validators:
- name: alice
  bonded: 100000000warp
