// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sequencer/sequencer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetLastArweaveBlockRequest struct {
}

func (m *QueryGetLastArweaveBlockRequest) Reset()         { *m = QueryGetLastArweaveBlockRequest{} }
func (m *QueryGetLastArweaveBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastArweaveBlockRequest) ProtoMessage()    {}
func (*QueryGetLastArweaveBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{2}
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastArweaveBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastArweaveBlockRequest.Merge(m, src)
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastArweaveBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastArweaveBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastArweaveBlockRequest proto.InternalMessageInfo

type QueryGetLastArweaveBlockResponse struct {
	LastArweaveBlock LastArweaveBlock `protobuf:"bytes,1,opt,name=LastArweaveBlock,proto3" json:"LastArweaveBlock"`
}

func (m *QueryGetLastArweaveBlockResponse) Reset()         { *m = QueryGetLastArweaveBlockResponse{} }
func (m *QueryGetLastArweaveBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastArweaveBlockResponse) ProtoMessage()    {}
func (*QueryGetLastArweaveBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{3}
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastArweaveBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastArweaveBlockResponse.Merge(m, src)
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastArweaveBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastArweaveBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastArweaveBlockResponse proto.InternalMessageInfo

func (m *QueryGetLastArweaveBlockResponse) GetLastArweaveBlock() LastArweaveBlock {
	if m != nil {
		return m.LastArweaveBlock
	}
	return LastArweaveBlock{}
}

type QueryGetLastSortKeyRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (m *QueryGetLastSortKeyRequest) Reset()         { *m = QueryGetLastSortKeyRequest{} }
func (m *QueryGetLastSortKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastSortKeyRequest) ProtoMessage()    {}
func (*QueryGetLastSortKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{4}
}
func (m *QueryGetLastSortKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastSortKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastSortKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastSortKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastSortKeyRequest.Merge(m, src)
}
func (m *QueryGetLastSortKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastSortKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastSortKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastSortKeyRequest proto.InternalMessageInfo

func (m *QueryGetLastSortKeyRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type QueryGetLastSortKeyResponse struct {
	LastSortKey LastSortKey `protobuf:"bytes,1,opt,name=lastSortKey,proto3" json:"lastSortKey"`
}

func (m *QueryGetLastSortKeyResponse) Reset()         { *m = QueryGetLastSortKeyResponse{} }
func (m *QueryGetLastSortKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastSortKeyResponse) ProtoMessage()    {}
func (*QueryGetLastSortKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{5}
}
func (m *QueryGetLastSortKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastSortKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastSortKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastSortKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastSortKeyResponse.Merge(m, src)
}
func (m *QueryGetLastSortKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastSortKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastSortKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastSortKeyResponse proto.InternalMessageInfo

func (m *QueryGetLastSortKeyResponse) GetLastSortKey() LastSortKey {
	if m != nil {
		return m.LastSortKey
	}
	return LastSortKey{}
}

type QueryAllLastSortKeyRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLastSortKeyRequest) Reset()         { *m = QueryAllLastSortKeyRequest{} }
func (m *QueryAllLastSortKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLastSortKeyRequest) ProtoMessage()    {}
func (*QueryAllLastSortKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{6}
}
func (m *QueryAllLastSortKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLastSortKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLastSortKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLastSortKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLastSortKeyRequest.Merge(m, src)
}
func (m *QueryAllLastSortKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLastSortKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLastSortKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLastSortKeyRequest proto.InternalMessageInfo

func (m *QueryAllLastSortKeyRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLastSortKeyResponse struct {
	LastSortKey []LastSortKey       `protobuf:"bytes,1,rep,name=lastSortKey,proto3" json:"lastSortKey"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLastSortKeyResponse) Reset()         { *m = QueryAllLastSortKeyResponse{} }
func (m *QueryAllLastSortKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLastSortKeyResponse) ProtoMessage()    {}
func (*QueryAllLastSortKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{7}
}
func (m *QueryAllLastSortKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLastSortKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLastSortKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLastSortKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLastSortKeyResponse.Merge(m, src)
}
func (m *QueryAllLastSortKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLastSortKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLastSortKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLastSortKeyResponse proto.InternalMessageInfo

func (m *QueryAllLastSortKeyResponse) GetLastSortKey() []LastSortKey {
	if m != nil {
		return m.LastSortKey
	}
	return nil
}

func (m *QueryAllLastSortKeyResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "sequencer.sequencer.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sequencer.sequencer.QueryParamsResponse")
	proto.RegisterType((*QueryGetLastArweaveBlockRequest)(nil), "sequencer.sequencer.QueryGetLastArweaveBlockRequest")
	proto.RegisterType((*QueryGetLastArweaveBlockResponse)(nil), "sequencer.sequencer.QueryGetLastArweaveBlockResponse")
	proto.RegisterType((*QueryGetLastSortKeyRequest)(nil), "sequencer.sequencer.QueryGetLastSortKeyRequest")
	proto.RegisterType((*QueryGetLastSortKeyResponse)(nil), "sequencer.sequencer.QueryGetLastSortKeyResponse")
	proto.RegisterType((*QueryAllLastSortKeyRequest)(nil), "sequencer.sequencer.QueryAllLastSortKeyRequest")
	proto.RegisterType((*QueryAllLastSortKeyResponse)(nil), "sequencer.sequencer.QueryAllLastSortKeyResponse")
}

func init() { proto.RegisterFile("sequencer/sequencer/query.proto", fileDescriptor_6cc648c12b425b9e) }

var fileDescriptor_6cc648c12b425b9e = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0xd5, 0x06, 0x9d, 0x80, 0xc8, 0xb4, 0x07, 0xd9, 0xca, 0x26, 0x2e, 0x68, 0x4a,
	0xa9, 0x3b, 0x26, 0xb5, 0xd2, 0x82, 0x14, 0x12, 0xc4, 0x0a, 0x0a, 0xc6, 0x78, 0x10, 0xbc, 0x84,
	0xc9, 0x3a, 0xac, 0xa1, 0x9b, 0x9d, 0xed, 0xce, 0xa4, 0x35, 0x14, 0x2f, 0x7e, 0x01, 0x05, 0xbf,
	0x87, 0x78, 0xf2, 0xea, 0x49, 0xe8, 0xb1, 0xe0, 0xc5, 0x93, 0x48, 0xe2, 0x07, 0x91, 0xcc, 0xbc,
	0x24, 0x9b, 0x64, 0xb7, 0x49, 0xbd, 0x4d, 0x66, 0xfe, 0xef, 0xfd, 0x7f, 0x93, 0xfd, 0xbf, 0x41,
	0x79, 0xc1, 0x0e, 0x3b, 0x2c, 0x70, 0x59, 0x44, 0xc6, 0xab, 0xc3, 0x0e, 0x8b, 0xba, 0x4e, 0x18,
	0x71, 0xc9, 0xf1, 0xca, 0x68, 0xdb, 0x19, 0xad, 0xcc, 0x55, 0x8f, 0x7b, 0x5c, 0x9d, 0x93, 0xc1,
	0x4a, 0x4b, 0xcd, 0x9b, 0x1e, 0xe7, 0x9e, 0xcf, 0x08, 0x0d, 0x5b, 0x84, 0x06, 0x01, 0x97, 0x54,
	0xb6, 0x78, 0x20, 0xe0, 0x74, 0xc3, 0xe5, 0xa2, 0xcd, 0x05, 0x69, 0x52, 0xc1, 0xb4, 0x03, 0x39,
	0x2a, 0x35, 0x99, 0xa4, 0x25, 0x12, 0x52, 0xaf, 0x15, 0x28, 0x31, 0x68, 0x0b, 0x49, 0x54, 0x21,
	0x8d, 0x68, 0x7b, 0xd8, 0x6d, 0x33, 0x49, 0xe1, 0x53, 0x21, 0x1b, 0x34, 0x3a, 0x66, 0xf4, 0x88,
	0x35, 0x9a, 0x3e, 0x77, 0x0f, 0x40, 0x5d, 0x4c, 0x55, 0x0b, 0x1e, 0xc9, 0xc6, 0x01, 0x83, 0xdb,
	0xda, 0xab, 0x08, 0xbf, 0x18, 0xa0, 0xd5, 0x94, 0x57, 0x7d, 0xa0, 0x15, 0xd2, 0xae, 0xa1, 0x95,
	0x89, 0x5d, 0x11, 0xf2, 0x40, 0x30, 0xbc, 0x8b, 0xb2, 0x9a, 0xe9, 0x86, 0x51, 0x30, 0xd6, 0x73,
	0xe5, 0x35, 0x27, 0xe1, 0xbf, 0x72, 0x74, 0x51, 0xf5, 0xf2, 0xe9, 0xef, 0x7c, 0xa6, 0x0e, 0x05,
	0xf6, 0x2d, 0x94, 0x57, 0x1d, 0xf7, 0x99, 0x7c, 0x46, 0x85, 0xac, 0x68, 0xe6, 0xea, 0x00, 0x79,
	0x68, 0x7a, 0x82, 0x0a, 0xe9, 0x12, 0x20, 0x78, 0x85, 0xae, 0x4f, 0x9f, 0x01, 0xcb, 0xed, 0x44,
	0x96, 0x69, 0x31, 0x50, 0xcd, 0x34, 0xb1, 0x77, 0x90, 0x19, 0x37, 0x7f, 0xc9, 0x23, 0xf9, 0x94,
	0x75, 0x01, 0x0d, 0x9b, 0xe8, 0x8a, 0xcb, 0x03, 0x19, 0x51, 0x57, 0x2a, 0xbb, 0xab, 0xf5, 0xd1,
	0x6f, 0xdb, 0x43, 0x6b, 0x89, 0x95, 0x40, 0xfc, 0x04, 0xe5, 0xfc, 0xf1, 0x36, 0xc0, 0x16, 0x52,
	0x61, 0x41, 0x07, 0x9c, 0xf1, 0x52, 0xfb, 0x0d, 0x20, 0x56, 0x7c, 0x3f, 0x01, 0xf1, 0x31, 0x42,
	0xe3, 0x54, 0x81, 0xcd, 0x1d, 0x47, 0x47, 0xd0, 0x19, 0x44, 0xd0, 0xd1, 0x21, 0x87, 0x08, 0x3a,
	0x35, 0xea, 0x31, 0xa8, 0xad, 0xc7, 0x2a, 0xed, 0xaf, 0x06, 0xdc, 0x67, 0xda, 0x26, 0xed, 0x3e,
	0x97, 0xfe, 0xf3, 0x3e, 0x78, 0x7f, 0x82, 0x78, 0x49, 0x11, 0x17, 0xe7, 0x12, 0x6b, 0x8c, 0x38,
	0x72, 0xf9, 0xc7, 0x32, 0x5a, 0x56, 0xc8, 0xf8, 0xa3, 0x81, 0xb2, 0x3a, 0x7e, 0xb8, 0x98, 0x88,
	0x34, 0x9b, 0x75, 0x73, 0x7d, 0xbe, 0x50, 0x7b, 0xda, 0xe5, 0x0f, 0x3f, 0xff, 0x7e, 0x5e, 0xda,
	0xc4, 0x1b, 0xe4, 0x98, 0x46, 0xe1, 0xdd, 0x61, 0x02, 0x04, 0x49, 0x1f, 0x5e, 0xfc, 0xdd, 0x98,
	0x4d, 0x2c, 0xbe, 0x9f, 0x6e, 0x99, 0x3e, 0x1f, 0xe6, 0xf6, 0x05, 0xab, 0x80, 0x7a, 0x4f, 0x51,
	0xef, 0xe0, 0x07, 0x8b, 0x50, 0xcf, 0x3e, 0x28, 0xf8, 0x9b, 0x81, 0x72, 0xb1, 0x2f, 0x89, 0xc9,
	0x5c, 0x8c, 0xc9, 0x64, 0x9a, 0xf7, 0x16, 0x2f, 0x00, 0xe4, 0x47, 0x0a, 0x79, 0x0f, 0x3f, 0x5c,
	0x18, 0x79, 0xf8, 0xaa, 0x91, 0x93, 0xa1, 0xf8, 0x3d, 0xfe, 0x62, 0xa0, 0x6b, 0xb1, 0xee, 0x15,
	0xdf, 0x3f, 0x8f, 0x3d, 0x71, 0xaa, 0xce, 0x63, 0x4f, 0x9e, 0x0f, 0x7b, 0x57, 0xb1, 0x6f, 0xe1,
	0xd2, 0x85, 0xd9, 0xab, 0xcf, 0x4f, 0x7b, 0x96, 0x71, 0xd6, 0xb3, 0x8c, 0x3f, 0x3d, 0xcb, 0xf8,
	0xd4, 0xb7, 0x32, 0x67, 0x7d, 0x2b, 0xf3, 0xab, 0x6f, 0x65, 0x5e, 0x6f, 0x7b, 0x2d, 0xf9, 0xb6,
	0xd3, 0x74, 0x5c, 0xde, 0x4e, 0x6f, 0xfb, 0x2e, 0xb6, 0x96, 0xdd, 0x90, 0x89, 0x66, 0x56, 0xbd,
	0xf1, 0x5b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x39, 0xde, 0x65, 0xf4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a LastArweaveBlock by index.
	LastArweaveBlock(ctx context.Context, in *QueryGetLastArweaveBlockRequest, opts ...grpc.CallOption) (*QueryGetLastArweaveBlockResponse, error)
	// Queries a list of LastSortKey items.
	LastSortKey(ctx context.Context, in *QueryGetLastSortKeyRequest, opts ...grpc.CallOption) (*QueryGetLastSortKeyResponse, error)
	LastSortKeyAll(ctx context.Context, in *QueryAllLastSortKeyRequest, opts ...grpc.CallOption) (*QueryAllLastSortKeyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastArweaveBlock(ctx context.Context, in *QueryGetLastArweaveBlockRequest, opts ...grpc.CallOption) (*QueryGetLastArweaveBlockResponse, error) {
	out := new(QueryGetLastArweaveBlockResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/LastArweaveBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastSortKey(ctx context.Context, in *QueryGetLastSortKeyRequest, opts ...grpc.CallOption) (*QueryGetLastSortKeyResponse, error) {
	out := new(QueryGetLastSortKeyResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/LastSortKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastSortKeyAll(ctx context.Context, in *QueryAllLastSortKeyRequest, opts ...grpc.CallOption) (*QueryAllLastSortKeyResponse, error) {
	out := new(QueryAllLastSortKeyResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/LastSortKeyAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a LastArweaveBlock by index.
	LastArweaveBlock(context.Context, *QueryGetLastArweaveBlockRequest) (*QueryGetLastArweaveBlockResponse, error)
	// Queries a list of LastSortKey items.
	LastSortKey(context.Context, *QueryGetLastSortKeyRequest) (*QueryGetLastSortKeyResponse, error)
	LastSortKeyAll(context.Context, *QueryAllLastSortKeyRequest) (*QueryAllLastSortKeyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LastArweaveBlock(ctx context.Context, req *QueryGetLastArweaveBlockRequest) (*QueryGetLastArweaveBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastArweaveBlock not implemented")
}
func (*UnimplementedQueryServer) LastSortKey(ctx context.Context, req *QueryGetLastSortKeyRequest) (*QueryGetLastSortKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastSortKey not implemented")
}
func (*UnimplementedQueryServer) LastSortKeyAll(ctx context.Context, req *QueryAllLastSortKeyRequest) (*QueryAllLastSortKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastSortKeyAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastArweaveBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastArweaveBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastArweaveBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/LastArweaveBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastArweaveBlock(ctx, req.(*QueryGetLastArweaveBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastSortKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastSortKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastSortKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/LastSortKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastSortKey(ctx, req.(*QueryGetLastSortKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastSortKeyAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLastSortKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastSortKeyAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/LastSortKeyAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastSortKeyAll(ctx, req.(*QueryAllLastSortKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sequencer.sequencer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LastArweaveBlock",
			Handler:    _Query_LastArweaveBlock_Handler,
		},
		{
			MethodName: "LastSortKey",
			Handler:    _Query_LastSortKey_Handler,
		},
		{
			MethodName: "LastSortKeyAll",
			Handler:    _Query_LastSortKeyAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencer/sequencer/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLastArweaveBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastArweaveBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastArweaveBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastArweaveBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastArweaveBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastArweaveBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LastArweaveBlock.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLastSortKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastSortKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastSortKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLastSortKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastSortKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastSortKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LastSortKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLastSortKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLastSortKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLastSortKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLastSortKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLastSortKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLastSortKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LastSortKey) > 0 {
		for iNdEx := len(m.LastSortKey) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastSortKey[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLastArweaveBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastArweaveBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LastArweaveBlock.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLastSortKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLastSortKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LastSortKey.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLastSortKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLastSortKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LastSortKey) > 0 {
		for _, e := range m.LastSortKey {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastArweaveBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastArweaveBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastArweaveBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastArweaveBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastSortKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastSortKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastSortKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastSortKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastSortKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastSortKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSortKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastSortKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLastSortKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLastSortKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLastSortKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLastSortKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLastSortKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLastSortKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSortKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastSortKey = append(m.LastSortKey, LastSortKey{})
			if err := m.LastSortKey[len(m.LastSortKey)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
