// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sequencer/sequencer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetLastArweaveBlockRequest struct {
}

func (m *QueryGetLastArweaveBlockRequest) Reset()         { *m = QueryGetLastArweaveBlockRequest{} }
func (m *QueryGetLastArweaveBlockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastArweaveBlockRequest) ProtoMessage()    {}
func (*QueryGetLastArweaveBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{2}
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastArweaveBlockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastArweaveBlockRequest.Merge(m, src)
}
func (m *QueryGetLastArweaveBlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastArweaveBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastArweaveBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastArweaveBlockRequest proto.InternalMessageInfo

type QueryGetLastArweaveBlockResponse struct {
	LastArweaveBlock LastArweaveBlock `protobuf:"bytes,1,opt,name=LastArweaveBlock,proto3" json:"LastArweaveBlock"`
}

func (m *QueryGetLastArweaveBlockResponse) Reset()         { *m = QueryGetLastArweaveBlockResponse{} }
func (m *QueryGetLastArweaveBlockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLastArweaveBlockResponse) ProtoMessage()    {}
func (*QueryGetLastArweaveBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{3}
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLastArweaveBlockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLastArweaveBlockResponse.Merge(m, src)
}
func (m *QueryGetLastArweaveBlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLastArweaveBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLastArweaveBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLastArweaveBlockResponse proto.InternalMessageInfo

func (m *QueryGetLastArweaveBlockResponse) GetLastArweaveBlock() LastArweaveBlock {
	if m != nil {
		return m.LastArweaveBlock
	}
	return LastArweaveBlock{}
}

type QueryGetPrevSortKeyRequest struct {
	Contract string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (m *QueryGetPrevSortKeyRequest) Reset()         { *m = QueryGetPrevSortKeyRequest{} }
func (m *QueryGetPrevSortKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPrevSortKeyRequest) ProtoMessage()    {}
func (*QueryGetPrevSortKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{4}
}
func (m *QueryGetPrevSortKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPrevSortKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPrevSortKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPrevSortKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPrevSortKeyRequest.Merge(m, src)
}
func (m *QueryGetPrevSortKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPrevSortKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPrevSortKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPrevSortKeyRequest proto.InternalMessageInfo

func (m *QueryGetPrevSortKeyRequest) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type QueryGetPrevSortKeyResponse struct {
	PrevSortKey PrevSortKey `protobuf:"bytes,1,opt,name=prevSortKey,proto3" json:"prevSortKey"`
}

func (m *QueryGetPrevSortKeyResponse) Reset()         { *m = QueryGetPrevSortKeyResponse{} }
func (m *QueryGetPrevSortKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPrevSortKeyResponse) ProtoMessage()    {}
func (*QueryGetPrevSortKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{5}
}
func (m *QueryGetPrevSortKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPrevSortKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPrevSortKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPrevSortKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPrevSortKeyResponse.Merge(m, src)
}
func (m *QueryGetPrevSortKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPrevSortKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPrevSortKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPrevSortKeyResponse proto.InternalMessageInfo

func (m *QueryGetPrevSortKeyResponse) GetPrevSortKey() PrevSortKey {
	if m != nil {
		return m.PrevSortKey
	}
	return PrevSortKey{}
}

type QueryAllPrevSortKeyRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPrevSortKeyRequest) Reset()         { *m = QueryAllPrevSortKeyRequest{} }
func (m *QueryAllPrevSortKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPrevSortKeyRequest) ProtoMessage()    {}
func (*QueryAllPrevSortKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{6}
}
func (m *QueryAllPrevSortKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPrevSortKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPrevSortKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPrevSortKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPrevSortKeyRequest.Merge(m, src)
}
func (m *QueryAllPrevSortKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPrevSortKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPrevSortKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPrevSortKeyRequest proto.InternalMessageInfo

func (m *QueryAllPrevSortKeyRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPrevSortKeyResponse struct {
	PrevSortKey []PrevSortKey       `protobuf:"bytes,1,rep,name=prevSortKey,proto3" json:"prevSortKey"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPrevSortKeyResponse) Reset()         { *m = QueryAllPrevSortKeyResponse{} }
func (m *QueryAllPrevSortKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPrevSortKeyResponse) ProtoMessage()    {}
func (*QueryAllPrevSortKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc648c12b425b9e, []int{7}
}
func (m *QueryAllPrevSortKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPrevSortKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPrevSortKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPrevSortKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPrevSortKeyResponse.Merge(m, src)
}
func (m *QueryAllPrevSortKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPrevSortKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPrevSortKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPrevSortKeyResponse proto.InternalMessageInfo

func (m *QueryAllPrevSortKeyResponse) GetPrevSortKey() []PrevSortKey {
	if m != nil {
		return m.PrevSortKey
	}
	return nil
}

func (m *QueryAllPrevSortKeyResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "sequencer.sequencer.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sequencer.sequencer.QueryParamsResponse")
	proto.RegisterType((*QueryGetLastArweaveBlockRequest)(nil), "sequencer.sequencer.QueryGetLastArweaveBlockRequest")
	proto.RegisterType((*QueryGetLastArweaveBlockResponse)(nil), "sequencer.sequencer.QueryGetLastArweaveBlockResponse")
	proto.RegisterType((*QueryGetPrevSortKeyRequest)(nil), "sequencer.sequencer.QueryGetPrevSortKeyRequest")
	proto.RegisterType((*QueryGetPrevSortKeyResponse)(nil), "sequencer.sequencer.QueryGetPrevSortKeyResponse")
	proto.RegisterType((*QueryAllPrevSortKeyRequest)(nil), "sequencer.sequencer.QueryAllPrevSortKeyRequest")
	proto.RegisterType((*QueryAllPrevSortKeyResponse)(nil), "sequencer.sequencer.QueryAllPrevSortKeyResponse")
}

func init() { proto.RegisterFile("sequencer/sequencer/query.proto", fileDescriptor_6cc648c12b425b9e) }

var fileDescriptor_6cc648c12b425b9e = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6b, 0x13, 0x4f,
	0x18, 0xc6, 0xb3, 0xfd, 0xff, 0x5b, 0xec, 0x14, 0x44, 0xa7, 0x3d, 0xc8, 0x56, 0x36, 0x71, 0x41,
	0x53, 0x42, 0xdd, 0x31, 0xa9, 0x95, 0x0a, 0x12, 0x48, 0x10, 0x2b, 0x28, 0x18, 0x23, 0x22, 0x78,
	0x09, 0x93, 0x75, 0x58, 0x43, 0x37, 0x3b, 0xdb, 0x99, 0x49, 0x6a, 0x28, 0x5e, 0xfc, 0x02, 0x0a,
	0x7e, 0x09, 0x4f, 0xd2, 0x93, 0x57, 0x4f, 0x42, 0x8f, 0x05, 0x2f, 0x9e, 0x44, 0x12, 0xc1, 0xaf,
	0x21, 0x3b, 0x3b, 0x49, 0xb6, 0xc9, 0x6c, 0x9a, 0x7a, 0x29, 0x6f, 0x67, 0x9f, 0xf7, 0x7d, 0x7e,
	0x33, 0x79, 0x66, 0x40, 0x96, 0x93, 0xfd, 0x0e, 0x09, 0x5c, 0xc2, 0xd0, 0xb8, 0xda, 0xef, 0x10,
	0xd6, 0x73, 0x42, 0x46, 0x05, 0x85, 0xab, 0xa3, 0x65, 0x67, 0x54, 0x99, 0x97, 0x71, 0xbb, 0x15,
	0x50, 0x24, 0xff, 0xc6, 0x3a, 0x73, 0xcd, 0xa3, 0x1e, 0x95, 0x25, 0x8a, 0x2a, 0xb5, 0x7a, 0xd5,
	0xa3, 0xd4, 0xf3, 0x09, 0xc2, 0x61, 0x0b, 0xe1, 0x20, 0xa0, 0x02, 0x8b, 0x16, 0x0d, 0xb8, 0xfa,
	0x5a, 0x70, 0x29, 0x6f, 0x53, 0x8e, 0x9a, 0x98, 0x93, 0xd8, 0x14, 0x75, 0x8b, 0x4d, 0x22, 0x70,
	0x11, 0x85, 0xd8, 0x6b, 0x05, 0x52, 0xac, 0xb4, 0x39, 0x1d, 0x68, 0x88, 0x19, 0x6e, 0x0f, 0xa7,
	0x6d, 0xea, 0x14, 0x3e, 0xe6, 0xa2, 0x81, 0xd9, 0x01, 0xc1, 0x5d, 0xd2, 0x68, 0xfa, 0xd4, 0xdd,
	0x53, 0xea, 0xbc, 0x76, 0x1e, 0x23, 0xdd, 0x06, 0xa7, 0x4c, 0x34, 0xf6, 0x88, 0x3a, 0x00, 0x7b,
	0x0d, 0xc0, 0xa7, 0x11, 0x5a, 0x4d, 0x7a, 0xd5, 0x23, 0x2d, 0x17, 0xf6, 0x73, 0xb0, 0x7a, 0x6a,
	0x95, 0x87, 0x34, 0xe0, 0x04, 0x96, 0xc1, 0x52, 0xcc, 0x74, 0xc5, 0xc8, 0x19, 0x1b, 0x2b, 0xa5,
	0x75, 0x47, 0x73, 0x7c, 0x4e, 0xdc, 0x54, 0x5d, 0x3e, 0xfe, 0x99, 0xcd, 0x7c, 0xfa, 0x73, 0x54,
	0x30, 0xea, 0xaa, 0xcb, 0xbe, 0x06, 0xb2, 0x72, 0xec, 0x2e, 0x11, 0x8f, 0x31, 0x17, 0x95, 0x18,
	0xbc, 0x1a, 0x71, 0x0f, 0x9d, 0x0f, 0x41, 0x2e, 0x5d, 0xa2, 0x30, 0x5e, 0x80, 0x4b, 0x93, 0xdf,
	0x14, 0xd0, 0x75, 0x2d, 0xd0, 0xa4, 0xb8, 0xfa, 0x7f, 0x84, 0x56, 0x9f, 0x1a, 0x62, 0xef, 0x00,
	0x73, 0x68, 0x5e, 0x63, 0xa4, 0xfb, 0x8c, 0x32, 0xf1, 0x88, 0xf4, 0x14, 0x1a, 0x34, 0xc1, 0x05,
	0x97, 0x06, 0x82, 0x61, 0x57, 0x48, 0xbb, 0xe5, 0xfa, 0xe8, 0x7f, 0xdb, 0x03, 0xeb, 0xda, 0x4e,
	0x45, 0xfc, 0x10, 0xac, 0x84, 0xe3, 0x65, 0x05, 0x9b, 0xd3, 0x9f, 0xde, 0x58, 0xa7, 0x38, 0x93,
	0xad, 0xf6, 0x2b, 0x85, 0x58, 0xf1, 0x7d, 0x0d, 0xe2, 0x03, 0x00, 0xc6, 0xd1, 0x52, 0x36, 0x37,
	0x9c, 0x38, 0x87, 0x4e, 0x94, 0x43, 0x27, 0x0e, 0xbf, 0xca, 0xa1, 0x53, 0xc3, 0x1e, 0x51, 0xbd,
	0xf5, 0x44, 0xa7, 0x7d, 0x64, 0xa8, 0xfd, 0x4c, 0xda, 0xa4, 0xed, 0xe7, 0xbf, 0x7f, 0xdc, 0x0f,
	0xdc, 0x3d, 0x45, 0xbc, 0x20, 0x89, 0xf3, 0x67, 0x12, 0xc7, 0x18, 0x49, 0xe4, 0xd2, 0xb7, 0x45,
	0xb0, 0x28, 0x91, 0xe1, 0x7b, 0x03, 0x2c, 0xc5, 0x19, 0x84, 0x79, 0x2d, 0xd2, 0x74, 0xe0, 0xcd,
	0x8d, 0xb3, 0x85, 0xb1, 0xa7, 0x5d, 0x7a, 0xf7, 0xfd, 0xf7, 0xc7, 0x85, 0x4d, 0x58, 0x40, 0x07,
	0x98, 0x85, 0x37, 0x87, 0x09, 0xe0, 0x28, 0xfd, 0x06, 0xc3, 0xaf, 0xc6, 0x74, 0x62, 0xe1, 0xed,
	0x74, 0xcb, 0xf4, 0xfb, 0x61, 0x6e, 0x9f, 0xb3, 0x4b, 0x51, 0x97, 0x25, 0xf5, 0x0e, 0xbc, 0x33,
	0x0f, 0xf5, 0xf4, 0xab, 0x02, 0xbf, 0x18, 0x60, 0x25, 0xf1, 0x4b, 0x42, 0x34, 0x13, 0x63, 0x3a,
	0x99, 0xe6, 0xad, 0xf9, 0x1b, 0x14, 0xf2, 0x7d, 0x89, 0x5c, 0x86, 0xf7, 0xe6, 0x3a, 0xe8, 0xe4,
	0xd3, 0x86, 0x0e, 0x87, 0xe2, 0xb7, 0xf0, 0xb3, 0x01, 0x2e, 0x26, 0xa6, 0x57, 0x7c, 0x7f, 0x16,
	0xbb, 0xf6, 0x56, 0xcd, 0x62, 0xd7, 0xdf, 0x0f, 0xfb, 0xae, 0x64, 0xdf, 0x82, 0xc5, 0x73, 0xb3,
	0x57, 0x9f, 0x1c, 0xf7, 0x2d, 0xe3, 0xa4, 0x6f, 0x19, 0xbf, 0xfa, 0x96, 0xf1, 0x61, 0x60, 0x65,
	0x4e, 0x06, 0x56, 0xe6, 0xc7, 0xc0, 0xca, 0xbc, 0xdc, 0xf6, 0x5a, 0xe2, 0x75, 0xa7, 0xe9, 0xb8,
	0xb4, 0x9d, 0x3e, 0xf6, 0x4d, 0xa2, 0x16, 0xbd, 0x90, 0xf0, 0xe6, 0x92, 0x7c, 0xe8, 0xb7, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xed, 0x6d, 0xe8, 0x62, 0x0c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a LastArweaveBlock by index.
	LastArweaveBlock(ctx context.Context, in *QueryGetLastArweaveBlockRequest, opts ...grpc.CallOption) (*QueryGetLastArweaveBlockResponse, error)
	// Queries a list of PrevSortKey items.
	PrevSortKey(ctx context.Context, in *QueryGetPrevSortKeyRequest, opts ...grpc.CallOption) (*QueryGetPrevSortKeyResponse, error)
	PrevSortKeyAll(ctx context.Context, in *QueryAllPrevSortKeyRequest, opts ...grpc.CallOption) (*QueryAllPrevSortKeyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastArweaveBlock(ctx context.Context, in *QueryGetLastArweaveBlockRequest, opts ...grpc.CallOption) (*QueryGetLastArweaveBlockResponse, error) {
	out := new(QueryGetLastArweaveBlockResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/LastArweaveBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PrevSortKey(ctx context.Context, in *QueryGetPrevSortKeyRequest, opts ...grpc.CallOption) (*QueryGetPrevSortKeyResponse, error) {
	out := new(QueryGetPrevSortKeyResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/PrevSortKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PrevSortKeyAll(ctx context.Context, in *QueryAllPrevSortKeyRequest, opts ...grpc.CallOption) (*QueryAllPrevSortKeyResponse, error) {
	out := new(QueryAllPrevSortKeyResponse)
	err := c.cc.Invoke(ctx, "/sequencer.sequencer.Query/PrevSortKeyAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a LastArweaveBlock by index.
	LastArweaveBlock(context.Context, *QueryGetLastArweaveBlockRequest) (*QueryGetLastArweaveBlockResponse, error)
	// Queries a list of PrevSortKey items.
	PrevSortKey(context.Context, *QueryGetPrevSortKeyRequest) (*QueryGetPrevSortKeyResponse, error)
	PrevSortKeyAll(context.Context, *QueryAllPrevSortKeyRequest) (*QueryAllPrevSortKeyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) LastArweaveBlock(ctx context.Context, req *QueryGetLastArweaveBlockRequest) (*QueryGetLastArweaveBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastArweaveBlock not implemented")
}
func (*UnimplementedQueryServer) PrevSortKey(ctx context.Context, req *QueryGetPrevSortKeyRequest) (*QueryGetPrevSortKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrevSortKey not implemented")
}
func (*UnimplementedQueryServer) PrevSortKeyAll(ctx context.Context, req *QueryAllPrevSortKeyRequest) (*QueryAllPrevSortKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrevSortKeyAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastArweaveBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLastArweaveBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastArweaveBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/LastArweaveBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastArweaveBlock(ctx, req.(*QueryGetLastArweaveBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PrevSortKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPrevSortKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PrevSortKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/PrevSortKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PrevSortKey(ctx, req.(*QueryGetPrevSortKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PrevSortKeyAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPrevSortKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PrevSortKeyAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.sequencer.Query/PrevSortKeyAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PrevSortKeyAll(ctx, req.(*QueryAllPrevSortKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sequencer.sequencer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LastArweaveBlock",
			Handler:    _Query_LastArweaveBlock_Handler,
		},
		{
			MethodName: "PrevSortKey",
			Handler:    _Query_PrevSortKey_Handler,
		},
		{
			MethodName: "PrevSortKeyAll",
			Handler:    _Query_PrevSortKeyAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencer/sequencer/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLastArweaveBlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastArweaveBlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastArweaveBlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetLastArweaveBlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLastArweaveBlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLastArweaveBlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LastArweaveBlock.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPrevSortKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPrevSortKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPrevSortKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPrevSortKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPrevSortKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPrevSortKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PrevSortKey.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPrevSortKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPrevSortKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPrevSortKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPrevSortKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPrevSortKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPrevSortKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PrevSortKey) > 0 {
		for iNdEx := len(m.PrevSortKey) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PrevSortKey[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLastArweaveBlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetLastArweaveBlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LastArweaveBlock.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPrevSortKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPrevSortKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PrevSortKey.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPrevSortKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPrevSortKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PrevSortKey) > 0 {
		for _, e := range m.PrevSortKey {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastArweaveBlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLastArweaveBlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLastArweaveBlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastArweaveBlock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastArweaveBlock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPrevSortKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPrevSortKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPrevSortKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPrevSortKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPrevSortKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPrevSortKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevSortKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PrevSortKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPrevSortKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPrevSortKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPrevSortKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPrevSortKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPrevSortKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPrevSortKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevSortKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevSortKey = append(m.PrevSortKey, PrevSortKey{})
			if err := m.PrevSortKey[len(m.PrevSortKey)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
